version: '3'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build: ./my-project
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
